config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'

  resources :restaurants, only: [:index, :show]

  namespace :owners do
    resources :restaurants
  end

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Course < ActiveRecord::Base
end

app/models/customer.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  phone_number           :string
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string
#  type                   :string
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

class Customer < User
  has_many :orders
end

app/models/owner.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  phone_number           :string
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string
#  type                   :string
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

class Owner < User
  has_many :restaurants
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :owner

end

app/models/seat.rb
# == Schema Information
#
# Table name: seats
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  course_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Seat < ActiveRecord::Base
  belongs_to :user 
  belongs_to :course
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id           :integer          not null, primary key
#  name         :string
#  phone_number :string
#  created_at   :datetime
#  updated_at   :datetime
#  email        :string
#

class User < ActiveRecord::Base
  has_many :posts
  has_many :seats
  has_many :courses, through: :seats

  validates_presence_of :name, :phone_number, :email
  validates_uniqueness_of :email
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners/orders_controller.rb
class Owner::OrdersController < AdminController
end

app/controllers/owners/restaurants_controller.rb
class Owners::RestaurantsController < AdminController
  def index
    @restaurants = current_user.restaurants
  end

  def new
    @restaurant = current_user.restaurants.new
  end

  def create
    current_user.restaurants.create(restaurant_params)
    redirect_to owners_restaurants_path
  end

  private 

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Startup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/restaurants/index.html.erb
<h1><%= "#{ current_user.name }'s Restaurants" %></h1>
<ul>
  <% @restaurants.each do |r| %>
    <li>
      <strong><%= r.name %></strong>
    </li>
  <% end %>
</ul>

<%= link_to 'create', new_owners_restaurant_path %>

app/views/owners/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= form_for [:owners, @restaurant] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to 'index', owners_restaurants_path %>

app/views/restaurants/index.html.erb
<h1>EAT FOOD</h1>
<ul>
  <% @restaurants.each do |r| %>
    <li>
      <strong><%= r.name %></strong>
      <div><%= r.owner.name %></div>
    </li>
  <% end %>
</ul>
<br/>

app/views/users/index.html.erb
<h1>Hi</h1>
<ul>
  <% @users.each do |u| %>
    <li><%= u.name %> - <%= u.email %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h4>Posts</h4>
<% @user.posts.each do |post| %>
  <h5><%= post.title %></h5>
  <p><%= post.text %></p>
<% end %>